### ISSUE TITLE
Add Help support (doc_items, etc.)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/unifieddyes#12]
I would appreciate if you help me in my quest to document all the things in Minetest by adding support for the Help mods (specifically doc_items) found here:

https://forum.minetest.net/viewtopic.php?f=9&t=15912&p=240152

Feel free to ask questions about the API if you need.

**Comment by VanessaE** [comment]
No github repo for this? :frowning_face:

**Comment by VanessaE** [comment]
\*looks at documentation\*

Each node/item in the game needs its own help text?  Homedecor has hundreds of nodes... no way am I going to do all of that.  Pull requests welcome.

**Comment by VanessaE** [comment]
...previous comment deleted, please ignore it.  I was mixing up mods.  Anyway, I don't think I'll be adding support in my mods for this help mod.  Too invasive, imho.

**Comment by Wuzzy2** [comment]
Too invasive? It is really just adding

```
_doc_items_longdesc = "Long item descripton/explanation goes here.", -- optional
_doc_items_usagehelp = "Explain here how to use this item.", -- optional
```

into the item definition table. There are some other possible fields, but they are all optional and I don't think they will be needed for this mod. The Help modpack has a big powerful API indeed, but everything is optional and most mods just need to use a small fraction of it.

See http://repo.or.cz/minetest_doc_example.git/tree for examples.

List of relevant repositories.

    doc: http://repo.or.cz/minetest_doc.git
    doc_items: http://repo.or.cz/minetest_doc_items.git

**Comment by VanessaE** [comment]
Less invasive would be if I could just include an appropriately-formatted text file, and some API call at the start of the mod to register that text file with the help mod.

**Comment by Wuzzy2** [comment]
I don't really see what's the point of this. I also don't understand why you see the syntax as some sort of “problem”, apparently. Adding custom fields to the node definition is officially encouraged, by the way.

A text file would only work for static help texts, but this modpack also supports dynamic help texts. Also, it would be impossible to translatable by `intllib`.
What I could do is to add a function to mass-add help texts to a list of item or something like that. Does this seem to make more sense to you.

**Comment by VanessaE** [comment]
I'm pretty sure that node definition items aren't really meant to carry long strings of text like that.  They're really meant to specify new attributes about a node, stuff some other mod can use to create new behavior.  Since I erroneously mentioned Home Decor earlier, let's just use that an example (because sooner or later, you were going to ask for support for the help mod therein :smile: ).  I would think one should be able to provide a simple text file that's just a list of the very node definition items you mentioned, but in a shorter and more collected-together form, e.g.:
```
node = "mymod:my_cool_node"
help = "This is the basic help text for my mod's cool node."

node = "mymod:some_name_*"
help = "This is the basic help text for all nodes that start with 'some_name'."
```

Now consider something like Unified Dyes, where usage is a global thing.  Why should I attach help text to each of the items provided by it, when they all behave the same way?  Rather, one should only need to provide a single text file describing the mod's usage.  If you want categories, follow the same pattern as above, e.g.:
```
category = "Crafting"
text = "This is the text describing how to craft a dye color"

category = "Coloring"
text = "This is the text describing how to color a node."

category = "Palettes"
text = "This is the text describing the various palettes supported by this mod."

category = "API"
text = "This is the text describing the mod's API."
```

The whole point is to avoid scattering help items all over the code.
