### ISSUE TITLE
Latest version of homedecor_modpack fails to recognized latest version of unifieddyes?

### ISSUE THREAD

**Issue by Guard13007** [minetest-mods/unifieddyes#17]
I'm not sure if this is an issue here or there or some incompatibility in what I'm doing (I'm very new to minetest and modding it, please let me know what I can do to test further and determine specific versions I'm using).

**Comment by VanessaE** [comment]
It works fine here.  The two are used together for example in Dreambuilder, which I just updated last night.

Please make sure you don't have an old copy of one or the other in your system somewhere.  Minetest searches all mod paths and only loads one copy of any given mod, usually from a modpack (such as DB), even if it's not the copy you told it to load.

**Comment by Guard13007** [comment]
Can you tell me what paths are searched? I have the win64 portable version,
I assumed it would be self-contained.

I will search my other packs for that possibility.

**Comment by VanessaE** [comment]
Minetest searches <minetest folder>/mods and if there are modpacks in there, those are checked first.

So if you have some modpack that contains a mod named "foo", and you also have a copy of "foo" sitting in just /mods, the copy inside the modpack will be loaded even if you didn't want it to.

**Comment by SnarkBoojum** [comment]
I also got a bug report on my Debian package, and found the following:
- activating only homedecor: the submodules depending on unifieddyes don't get activated by the game since the dependency is missing
- activating only unifieddyes: ok
- activating both homedecor and unifieddyes: the submodules of homedecor depending on unifieddyes trigger an error because "unifieddyes" is nil.

My explanation of the problem is the following: if unifieddyes hasn't been activated, the game doesn't try to run the homedecor submodules depending on it. But if it has been activated, then the game thinks it's actually available and tries to run the homedecor submodules depending on it. But the unifieddyes module doesn't define the unifieddyes global! So this is where the problem occurs.

Looking around... I see that my package lacks the api which homedecor expects... because I'm packaging the last version of unifieddyes, which doesn't have the api : it's only available from git checkouts!

So the solution to this issue is simple: tag a new release, and then the latest release of unifieddyes will work with the latest release of homedecor! :-P

Thanks!

**Comment by VanessaE** [comment]
Done.  Look for tag `stable-20170925` on both projects.

**Comment by SnarkBoojum** [comment]
Ah, does that mean I should detect the stable-<date> tags to be notified of all future stable versions?

**Comment by SnarkBoojum** [comment]
Hmmm... I had a look and indeed stable-  tags are what had been used since a few versions : I'll modify my package to detect those and follow more easily. Thanks!

**Comment by VanessaE** [comment]
That's probably a good idea.  Or really, just always pick the newest tag, as I will be trying to only tag the code when I think it's stable, but I may not always be consistent with the actual naming of such.

**Comment by SnarkBoojum** [comment]
No, not the newest tag : I need a consistent versioning. The stable-date format is perfect. Thanks!

**Comment by VanessaE** [comment]
Ok then.  Enjoy :)

Bear in mind that occasionally it might be `stable-$date-` followed by one or two more digits, in case I notice an error after tagging, and need to make another release that same day.

**Comment by SnarkBoojum** [comment]
Oh, good, I'll correct my watch file to handle that too. Thanks!

**Comment by SnarkBoojum** [comment]
Uh... now that I think of it, a scheme with one or two digits is problematic since a -3 will be seen as newer that a -10 as far as I understand. Or well, let's hope you never reach that high a number of revisions in a same day :-P

**Comment by VanessaE** [comment]
For now, it's safe to assume it'll be a single digit. :smile:
